export { default as BerandaSkeleton } from './BerandaSkeleton';
export { LowonganSkeleton, MyLowonganSkeleton } from './LowonganSkeleton';
export { default as AlumniSkeleton } from './AlumniSkeleton';
export { default as ProfilSkeleton } from './ProfilSkeleton';
export { default as LowonganDetailSkeleton } from './LowonganDetailSkeleton';
export { default as AlumniDetailSkeleton } from './AlumniDetailSkeleton';
export { default as PengumumanDetailSkeleton } from './PengumumanDetail';
export { default as NotifikasiSkeleton } from './NotifikasiSkeleton';
export { default as KuesionerSkeleton } from './KuesionerSkeleton';
export { default as PostinganSkeleton } from './PostinganSkeleton';